//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItCompanyInfocarat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Done_applications
    {
        public int id_done_application { get; set; }
        public int id_application { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    
        public virtual Applications Applications { get; set; }
    }
}
